# OBS Instance that will send and drive the volume mixer for both instances
[primary]
host = "0.0.0.0" # Local IP Address of Primary OBS Instance
port = 4455 # Local Port of  Primary OBS Instance
password = "password" # OBS Websocket Password of Primary OBS Instance

# OBS Instance that will receive and follow the volume mixer
[secondary]
host = "0.0.0.0" # Local IP Address of Secondary OBS Instance
port = 4455 # Local Port of Secondary OBS Instance
password = "password" # OBS Websocket Password of Secondary OBS Instance
